app:
  token: fillme
  rts-url: fillme
# ===============================
# DB CONNECTION
# ===============================
spring.datasource.url: jdbc:postgresql://localhost:5432/reschedule-tsu-vk
spring.datasource.username: postgres
spring.datasource.password: postgres
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.default_schema: public
spring.jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false