app:
  vk:
    group-id: 0
    token: ---
    use-callback-api: true
    secret-confirm: ---
    secret-key: ---
  rts-url: ---
  text-query:
    activate-dialogflow: false  # googlecredentials.json must be in classpath for 'true'
    credentials-path: classpath:googlecredentials.json
  red-faculties: [ ]
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
# ===============================
# DB CONNECTION
# ===============================
spring.datasource.url: ---
spring.datasource.username: ---
spring.datasource.password: ---
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.default_schema: public
spring.jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false